# Email SMTP
spring.mail.host=smtp.seudominio.com
spring.mail.port=587
spring.mail.username=usuario@seudominio.com
spring.mail.password=senha
spring.mail.protocol=smtp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.mail.url=http://localhost:8001

spring.application.name=SCD_API_HEXA
# server.port=8001



# datasource

spring.datasource.driverClassName=oracle.jdbc.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@sptscddb01T.sptrans.corp:1521/SPSCD
spring.datasource.username=SCD_WEB
spring.datasource.password=6JCoTb13lRL3
# spring.datasource.jndi-name=jdbc/OracleSCD



#para testes locais

spring.profiles.active=local


# jpa

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.enable_lazy_load_no_trans=true


#trata os problemas com sequence
spring.jpa.hibernate.use-new-id-generator-mappings=false 


#BUG DO HIBERNATE
logger.org.hibernate.dialect.function.TemplateRenderer.level=ERROR

# logging
logging.level.root=WARN
logging.level.br.=DEBUG
logging.level.org.hibernate.SQL=WARN
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
spring.jpa.open-in-view=false


#infos da aplicao

app.version=@project.version@
spring.thymeleaf.check-template-location=false
