-- Script para criar a tabela password_reset_tokens correspondente à entidade PasswordTokenEntityJpa
CREATE TABLE SPTRANSDBA.reset_tokens (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    token VARCHAR2(36 CHAR) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    used NUMBER(1) DEFAULT 0 NOT NULL,
    dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Índice único já garantido pela constraint UNIQUE em token
ALTER TABLE SPTRANSDBA.reset_tokens ADD CONSTRAINT fk_password_token_usuario FOREIGN KEY (id_usuario) REFERENCES SPTRANSDBA.USUARIOS(id);
