-- ============================================================
-- DDL: Tabela de Sessões de Usuários
-- Schema: SPTRANSDBA
-- Executar no banco Oracle antes de subir a aplicação.
-- ============================================================

CREATE TABLE SPTRANSDBA.SCD_SESSIONS_USUARIOS (
    ID_SESSAO         VARCHAR2(36)   NOT NULL,
    ID_USUARIO        NUMBER(19)     NOT NULL,
    ENDERECO_IP       VARCHAR2(45),
    AGENTE_USUARIO    VARCHAR2(500),
    DT_CRIACAO        TIMESTAMP      NOT NULL,
    DT_EXPIRACAO      TIMESTAMP      NOT NULL,
    DT_REVOGACAO      TIMESTAMP,
    MOTIVO_REVOGACAO  VARCHAR2(100),
    ID_REVOGADO_POR   NUMBER(19),

    CONSTRAINT PK_SCD_SESSIONS_USUARIOS PRIMARY KEY (ID_SESSAO),
    CONSTRAINT FK_SCD_SESSIONS_USUARIOS_USUARIO    FOREIGN KEY (ID_USUARIO)
        REFERENCES SPTRANSDBA.USUARIOS (ID_USUARIO)
);

-- Índices para consultas frequentes
CREATE INDEX IDX_SCD_SESSIONS_USUARIOS_ID_USUARIO    ON SPTRANSDBA.SCD_SESSIONS_USUARIOS (ID_USUARIO);
CREATE INDEX IDX_SCD_SESSIONS_USUARIOS_DT_EXPIRACAO  ON SPTRANSDBA.SCD_SESSIONS_USUARIOS (DT_EXPIRACAO);
CREATE INDEX IDX_SCD_SESSIONS_USUARIOS_REVOGACAO     ON SPTRANSDBA.SCD_SESSIONS_USUARIOS (DT_REVOGACAO, ID_USUARIO);
