-- Script para criar a tabela password_reset_tokens correspondente à entidade PasswordTokenEntityJpa
CREATE TABLE SPTRANSDBA.reset_tokens (
    id NUMBER GENERATED BY  DEFAULT SPTRANSDBA.seq_password_reset_tokens_id.NEXTVAL PRIMARY KEY,
    id_usuario NUMBER NOT NULL,
    token VARCHAR2(36 CHAR) NOT NULL UNIQUE,
    expiry_date TIMESTAMP NOT NULL,
    used NUMBER(1) DEFAULT 0 NOT NULL,
    dt_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Sequence para ser usada na tabela password_reset_tokens
CREATE SEQUENCE SPTRANSDBA.seq_password_reset_tokens_id
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Para usar a sequence na coluna id ao inserir:
-- INSERT INTO SPTRANSDBA.password_reset_tokens (id, ...) VALUES (SPTRANSDBA.seq_password_reset_tokens_id.NEXTVAL, ...);

-- Índice único já garantido pela constraint UNIQUE em token
-- Adicione FK para id_usuario se necessário, exemplo:
-- ALTER TABLE SPTRANSDBA.password_reset_tokens ADD CONSTRAINT fk_password_token_usuario FOREIGN KEY (id_usuario) REFERENCES SPTRANSDBA.usuario(id);
