-- ============================================================
-- DDL: Tabela de Sessões de Usuários
-- Schema: SPTRANSDBA
-- Executar no banco Oracle antes de subir a aplicação.
-- ============================================================

CREATE TABLE SPTRANSDBA.USER_SESSIONS (
    ID_SESSAO         VARCHAR2(36)   NOT NULL,
    ID_USUARIO        NUMBER(19)     NOT NULL,
    ENDERECO_IP       VARCHAR2(45),
    AGENTE_USUARIO    VARCHAR2(500),
    DT_CRIACAO        TIMESTAMP      NOT NULL,
    DT_EXPIRACAO      TIMESTAMP      NOT NULL,
    DT_REVOGACAO      TIMESTAMP,
    MOTIVO_REVOGACAO  VARCHAR2(100),
    ID_REVOGADO_POR   NUMBER(19),

    CONSTRAINT PK_USER_SESSIONS PRIMARY KEY (ID_SESSAO),
    CONSTRAINT FK_US_USUARIO    FOREIGN KEY (ID_USUARIO)
        REFERENCES SPTRANSDBA.USUARIOS (ID_USUARIO)
);

-- Índices para consultas frequentes
CREATE INDEX IDX_US_ID_USUARIO    ON SPTRANSDBA.USER_SESSIONS (ID_USUARIO);
CREATE INDEX IDX_US_DT_EXPIRACAO  ON SPTRANSDBA.USER_SESSIONS (DT_EXPIRACAO);
CREATE INDEX IDX_US_REVOGACAO     ON SPTRANSDBA.USER_SESSIONS (DT_REVOGACAO, ID_USUARIO);
