INSERT ALL
    INTO SPTRANSDBA.MODULOS (
        COD_SISTEMA, COD_MODULO, ID_USUARIO_MANUTENCAO, DT_MODI, NOM_MODULO, COD_STATUS, NOM_EXECUTAVEL
    ) VALUES ('SCD_WEB_API', 'CAC', 1, SYSDATE, 'Cadastro e Controle', 'A', 'cac.exe')
    INTO SPTRANSDBA.MODULOS (COD_SISTEMA, COD_MODULO, ID_USUARIO_MANUTENCAO, DT_MODI, NOM_MODULO, COD_STATUS, NOM_EXECUTAVEL)
        VALUES ('SCD_WEB_API', 'CAD', 1, SYSDATE, 'Cadastro', 'A', 'cad.exe')
    INTO SPTRANSDBA.MODULOS (COD_SISTEMA, COD_MODULO, ID_USUARIO_MANUTENCAO, DT_MODI, NOM_MODULO, COD_STATUS, NOM_EXECUTAVEL)
        VALUES ('SCD_WEB_API', 'PEDCR', 1, SYSDATE, 'Pedidos de Crédito', 'A', 'pedcr.exe')
    INTO SPTRANSDBA.MODULOS (COD_SISTEMA, COD_MODULO, ID_USUARIO_MANUTENCAO, DT_MODI, NOM_MODULO, COD_STATUS, NOM_EXECUTAVEL)
        VALUES ('SCD_WEB_API', 'CARTAO', 1, SYSDATE, 'Cartões Inicializados', 'A', 'initialcard.exe')
    INTO SPTRANSDBA.MODULOS (COD_SISTEMA, COD_MODULO, ID_USUARIO_MANUTENCAO, DT_MODI, NOM_MODULO, COD_STATUS, NOM_EXECUTAVEL)
        VALUES ('SCD_WEB_API', 'PRO', 1, SYSDATE, 'Produtos', 'A', 'pro.exe')
SELECT * FROM dual;
