SELECT * 
FROM all_constraints
WHERE constraint_name = 'SYS_C0027360';

SELECT table_name, column_name
FROM all_cons_columns
WHERE constraint_name = 'SYS_C0027344';


INSERT  INTO SPTRANSDBA.PERFIL_FUNCIONALIDADES (COD_SISTEMA, COD_MODULO, COD_ROTINA, COD_FUNCIONALIDADE, COD_PERFIL, ID_USUARIO_MANUTENCAO, DT_INICIO_VALIDADE)
         VALUES ('SCD_WEB_API', 'CAC', 'USU', 'LISASSUSUPER', 'ADMIN', 1, SYSDATE);